scan_timeout = 60
add_newline = false

[line_break]
disabled = true

[username]
format = '[$user]($style)'
disabled = false
show_always = false

[hostname]
ssh_only = true
format = '[$ssh_symbol$hostname]($style) '

[cmd_duration]
format = "[$duration]($style) "

[status]
disabled = false
format = "[$symbol $status]($style) "
not_found_symbol = ""
not_executable_symbol = ""
sigint_symbol = "ﭦ"
map_symbol = true

[directory]
style = "bold blue"

[sudo]
format = '[$symbol]($style)'
style = 'bold red'
symbol = ' '
disabled = false

[git_branch]
format = "[$symbol$branch]($style) "

[package]
format = "[$symbol$version]($style) "
symbol = " "

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "

[nodejs]
format = "[$symbol($version )]($style)"

[php]
format = "[$symbol($version )]($style)"
symbol = " "

[java]
format = "[${symbol}(${version} )]($style)"
symbol = " "

[rust]
format = "[$symbol($version )]($style)"

[golang]
format = "[$symbol($version )]($style)"
symbol = " "

